/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIDepuracionCognitivo.java
 *
 * Created on 13-dic-2011, 13:28:34
 */

package icaro.aplicaciones.recursos.recursoDepuracionCognitivo.imp;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Jose
 */
public class GUIDepuracionCognitivo extends javax.swing.JFrame {

    /** Creates new form GUIDepuracionCognitivo */
    public GUIDepuracionCognitivo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(textArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void mostrarInfoTextArea(String s){
        this.textArea1.append(s);        
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDepuracionCognitivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

    public java.awt.TextArea getTextArea(){
        return this.textArea1;
    }

    //Cambiar el fondo del componente TextArea
    public void setBackgroundTextArea(Color c){
    	this.textArea1.setBackground(c);            	
    }


    //Cambiar el color de la letra del componente TextArea    
    public void setForegroundTextArea(Color c){
    	this.textArea1.setForeground(c);
    }

    
    //Cambiar la fuente del tipo de letra del componente TextArea   
    public void setFontTextArea(Font f){
    	this.textArea1.setFont(f);
    }
    
}
