FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_4robots_10victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_4robots_15victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_4robots_20victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_6robots_10victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_8robots_10victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_6robots_16victimas_CASA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_2robots_6victimas_LLANURA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_4robots_6victimas_LLANURA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_6robots_6victimas_LLANURA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_6robots_12victimas_LLANURA %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_4robots_14victimas_ESTADIO %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_6robots_14victimas_ESTADIO %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_8robots_14victimas_ESTADIO %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_8robots_17victimas_ESTADIO %%A
FOR %%A IN (1,2,3) DO java -jar demo.jar descripcion_8robots_20victimas_ESTADIO %%A