//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.26 at 01:54:43 AM CET 
//


package icaro.aplicaciones.informacion.dominioClases.asistente;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponenteGestionado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponenteGestionado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="refId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refDescripcion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipoComponente" use="required" type="{urn:icaro:aplicaciones:descripcionOrganizaciones}TipoComponente" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponenteGestionado")
public class ComponenteGestionado {

    @XmlAttribute(required = true)
    protected String refId;
    @XmlAttribute
    protected String refDescripcion;
    @XmlAttribute(required = true)
    protected TipoComponente tipoComponente;

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the refDescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDescripcion() {
        return refDescripcion;
    }

    /**
     * Sets the value of the refDescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDescripcion(String value) {
        this.refDescripcion = value;
    }

    /**
     * Gets the value of the tipoComponente property.
     * 
     * @return
     *     possible object is
     *     {@link TipoComponente }
     *     
     */
    public TipoComponente getTipoComponente() {
        return tipoComponente;
    }

    /**
     * Sets the value of the tipoComponente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoComponente }
     *     
     */
    public void setTipoComponente(TipoComponente value) {
        this.tipoComponente = value;
    }

}
