//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.26 at 01:54:43 AM CET 
//


package icaro.aplicaciones.informacion.dominioClases.asistente;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescRecursosAplicacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescRecursosAplicacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DescRecursoAplicacion" type="{urn:icaro:aplicaciones:descripcionOrganizaciones}DescRecursoAplicacion" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescRecursosAplicacion", propOrder = {
    "descRecursoAplicacion"
})
public class DescRecursosAplicacion {

    @XmlElement(name = "DescRecursoAplicacion")
    protected List<DescRecursoAplicacion> descRecursoAplicacion;

    /**
     * Gets the value of the descRecursoAplicacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descRecursoAplicacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescRecursoAplicacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescRecursoAplicacion }
     * 
     * 
     */
    public List<DescRecursoAplicacion> getDescRecursoAplicacion() {
        if (descRecursoAplicacion == null) {
            descRecursoAplicacion = new ArrayList<DescRecursoAplicacion>();
        }
        return this.descRecursoAplicacion;
    }

    public void setDescRecursoAplicacion(ArrayList<DescRecursoAplicacion> descRecursoAplicacion) {
        this.descRecursoAplicacion = descRecursoAplicacion;
    }

   
   

}
