//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.26 at 01:54:43 AM CET 
//


package icaro.aplicaciones.informacion.dominioClases.asistente;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoAgente.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoAgente">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Cognitivo"/>
 *     &lt;enumeration value="CognitivoConExpectativas"/>
 *     &lt;enumeration value="Reactivo"/>
 *     &lt;enumeration value="ReactivoSCXML"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoAgente")
@XmlEnum
public enum TipoAgente {

    @XmlEnumValue("Cognitivo")
    COGNITIVO("Cognitivo"),
    @XmlEnumValue("CognitivoConExpectativas")
    COGNITIVO_CON_EXPECTATIVAS("CognitivoConExpectativas"),
    @XmlEnumValue("Reactivo")
    REACTIVO("Reactivo"),
    @XmlEnumValue("ReactivoSCXML")
    REACTIVO_SCXML("ReactivoSCXML");
    private final String value;

    TipoAgente(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoAgente fromValue(String v) {
        for (TipoAgente c: TipoAgente.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
